config/routes.rb
Rails.application.routes.draw do
#  get 'home_info_enquiries/index'

#  get 'home_info_enquiries/new'

 # get 'home_info_enquiries/create'

  devise_for :users, controllers: { registrations: "registrations"}
 #get 'home' => 'pages#home' 
# match "pages/:id", to: "homepage#home", as: "home_page"
# get 'search' => 'pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home_photos
  resources :homes 
  resources :home_info_enqueries
#  resources :home_info_enqueries, only: [:create, :edit, :delete]
  
#  resources  :contact_pages, :only => [:create , :index]
  resources :pages , :only => [:index, :new, :create]
   # get 'single_wide'
#    get 'singe_wide' => 'pages#single_wide'
#  match "/pages/single_wide " => "pages#single_wide", :as => 'single_wide'     
  
  get 'pages/single_wide' => 'pages#single_wide', :as => 'single_wide'
  get 'pages/double_wide' => 'pages#double_wide', :as => 'double_wide'
  get 'pages/triple_wide' => 'pages#triple_wide', :as => 'triple_wide'
  get 'pages/other' => 'pages#other', :as => 'other'
  get 'pages/hotdeals' => 'pages#hotdeals', :as => 'hotdeals'
  post 'pages/search' => 'pages#search' , :as => 'search'
  root :to => "homes#index"
  get 'contact_pages' => 'contact_pages#new', :as => 'contact_pages'
  post 'contact_pages' => 'contact_pages#create'
 
#  post 'contact' => 'contact_pages#create'
#  get 'singe_wide', to: 'pages#single_wide'
end

app/views/pages/_home_photos.erb
<h3> in the partial </h3>

app/views/pages/double_wide.html.erb
v style="margin-top:25px; margin-bottom:150px;">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				<ul class="sidebar-list">
					<li class="sidebar-item"><%= link_to "Homes", homes_path, class:"sidebar-link active"%></li>
					
					
				</ul>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading" style="background-color:#6dae4e;">
						Homes(<%= @double_wide.length %>)
					</div>
                                        <% if @double_wide.present? && @double_wide.size > 0 %>
					<div class="panel-body">
							<% @double_wide.each do |home| %>
							<div class="row">
								<div class="col-md-2">
									<%= image_tag home.home_photos[0].image.url(:thumb) if home.home_photos.length > 0 %>
								</div>
								<div class="col-md-2">
									<h4><%= link_to home.name, home %></h4>
								</div>
								<div class="col-md-3 right">
									<%= link_to "Edit", edit_home_path(home), class: "btn btn-green"%>
								</div>
							</div>
							<hr/>
						<% end %>
					</div>
                                <% else %>

                        <h3> no record found </h3>
                          <% end %>
				</div>
			</div>	
		</div>
	</div>
</div>

app/views/pages/hotdeals.html.erb
<div style="margin-top:25px; margin-bottom:150px;">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				<ul class="sidebar-list">
					<li class="sidebar-item"><%= link_to "Homes", homes_path, class:"sidebar-link active"%></li>
					
					
				</ul>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading" style="background-color:#6dae4e;">
						Homes(<%= @hotdeals.length %>)
					</div>
                                        <% if @double_wide.present? && @double_wide.size > 0 %>
					<div class="panel-body">
							<% @hotdeals.each do |home| %>
							<div class="row">
								<div class="col-md-2">
									<%= image_tag home.home_photos[0].image.url(:thumb) if home.home_photos.length > 0 %>
								</div>
								<div class="col-md-2">
									<h4><%= link_to home.name, home %></h4>
								</div>
								<div class="col-md-3 right">
									<%= link_to "Edit", edit_home_path(home), class: "btn btn-green"%>
								</div>
							</div>
							<hr/>
						<% end %>
					</div>
                                <% else %>

                        <h3> no record found </h3>
                          <% end %>
				</div>
			</div>	
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<%= form_tag search_path do %>
  <label for="lookup">Lookup</label>

  <%= select_tag :select_home, options_for_select([["Single wide","Single wide"], ["Double wide","Double wide"], ["Triple wide","Triple wide"],["Hot Deals","Hot deals"]]) %>
 <%= submit_tag "Submit" %>
<% end %>

app/views/pages/new.html.erb
<%= form_for @select_home do |f| %>
<%= f.select :select_home, [["Single wide","Single wide"], ["Double wide","Double wide"], ["Triple wide","Triple wide"],
                                                ["Others","Others"],
                                                 ["Hot deals","Hot deals"],
                                        ], id: 'home_type', prompt: 'Select...', :required => false, class: 'form-control' %>

<%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>


<%= form_tag search_path do %>
  <label for="lookup">Lookup</label>
 
  <%= select_tag :select_home, options_for_select([["Single wide","Single wide"], ["Double wide","Double wide"], ["Triple wide","Triple wide"]]) %>
 <%= submit_tag "Submit" %>
<% end %>

app/views/pages/other.html.erb
<div style="margin-top:25px; margin-bottom:150px;">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				<ul class="sidebar-list">
					<li class="sidebar-item"><%= link_to "Homes", homes_path, class:"sidebar-link active"%></li>
					
					
				</ul>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading" style="background-color:#6dae4e;">
						Homes(<%= @other.length %>)
					</div>
                                        <% if @double_wide.present? && @double_wide.size > 0 %>
					<div class="panel-body">
							<% @other.each do |home| %>
							<div class="row">
								<div class="col-md-2">
									<%= image_tag home.home_photos[0].image.url(:thumb) if home.home_photos.length > 0 %>
								</div>
								<div class="col-md-2">
									<h4><%= link_to home.name, home %></h4>
								</div>
								<div class="col-md-3 right">
									<%= link_to "Edit", edit_home_path(home), class: "btn btn-green"%>
								</div>
							</div>
							<hr/>
						<% end %>
					</div>
                                <% else %>

                        <h3> no record found </h3>
                          <% end %>
				</div>
			</div>	
		</div>
	</div>
</div>

app/views/pages/single_wide.html.erb
<div style="margin-top:25px; margin-bottom:150px;">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				<ul class="sidebar-list">
					<li class="sidebar-item"><%= link_to "Homes", homes_path, class:"sidebar-link active"%></li>
					
					
				</ul>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading" style="background-color:#6dae4e;">
						Homes(<%= @single_wide.length %>)
					</div>
					<div class="panel-body">
							<% @single_wide.each do |home| %>
							<div class="row">
								<div class="col-md-2">
									<%= image_tag home.home_photos[0].image.url(:thumb) if home.home_photos.length > 0 %>
								</div>
								<div class="col-md-2">
									<h4><%= link_to home.name, home %></h4>
								</div>
								<div class="col-md-3 right">
									<%= link_to "Edit", edit_home_path(home), class: "btn btn-green"%>
								</div>
							</div>
							<hr/>
						<% end %>
					</div>
				</div>
			</div>	
		</div>
	</div>
</div>

app/views/pages/triple_wide.html.erb
<div style="margin-top:25px; margin-bottom:150px;">
	<div class="container">
		<div class="row">
			<div class="col-md-2">
				<ul class="sidebar-list">
					<li class="sidebar-item"><%= link_to "Homes", homes_path, class:"sidebar-link active"%></li>
					
					
				</ul>
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading" style="background-color:#6dae4e;">
						Homes(<%= @triple_wide.length %>)
					</div>
                                        <% if @double_wide.present? && @double_wide.size > 0 %>
					<div class="panel-body">
							<% @triple_wide.each do |home| %>
							<div class="row">
								<div class="col-md-2">
									<%= image_tag home.home_photos[0].image.url(:thumb) if home.home_photos.length > 0 %>
								</div>
								<div class="col-md-2">
									<h4><%= link_to home.name, home %></h4>
								</div>
								<div class="col-md-3 right">
									<%= link_to "Edit", edit_home_path(home), class: "btn btn-green"%>
								</div>
							</div>
							<hr/>
						<% end %>
					</div>
                                <% else %>

                        <h3> no record found </h3>
                          <% end %>
				</div>
			</div>	
		</div>
	</div>
</div>